#!/usr/bin/env bash

# python3 ../odoo_export_thread.py -c conf/connection_download.conf --file=retrieved/purchase.order.csv --model='purchase.order' --worker=1 --size=200 --domain="[]" --field="id,name,picking_type_id:id,date_order,origin,partner_id:id,fiscal_position_id:id,user_id:id,payment_term_id:id,date_order,date_planned,state,limit_amount,invoice_status,date_approve" --sep=";" --encoding=utf-8-sig
# python3 ../odoo_export_thread.py -c conf/connection_download.conf --file=retrieved/purchase.order.line.csv --model='purchase.order.line' --worker=1 --size=200 --domain="[]" --field="id,name,date_planned,discount,taxes_id:id,price_unit,product_id:id,order_id:id,sequence,state,product_uom:id,qty_invoiced,qty_received,qty_to_invoice,qty_to_receive,product_qty" --sep=";" --encoding=utf-8-sig
# python3 ../odoo_export_thread.py -c conf/connection_download.conf --file=retrieved/sale.order.csv --model='sale.order' --worker=1 --size=200 --domain="[]" --field="id,name,partner_id:id,type_order,partner_invoice_id:id,partner_shipping_id:id,confirmation_date,pricelist_id:id,payment_term_id:id,client_order_ref,array_id:id,state,fiscal_position_id:id,invoice_status,force_invoiced,warehouse_id:id,user_id:id,agent_id:id,team_id:id,date_order" --sep=";" --encoding=utf-8-sig
# python3 ../odoo_export_thread.py -c conf/connection_download.conf --file=retrieved/sale.order_update.csv --model='sale.order' --worker=1 --size=200 --domain="['|',['__last_update',&gt;,'2020-05-15 15:30:00'],['create_date',&gt;,'2020-05-15 15:30:00']]" --field="id,__last_update,create_date,name,partner_id:id,type_order,partner_invoice_id:id,partner_shipping_id:id,confirmation_date,pricelist_id:id,payment_term_id:id,client_order_ref,array_id:id,state,fiscal_position_id:id,invoice_status,force_invoiced,warehouse_id:id,user_id:id,agent_id:id,team_id:id,date_order" --sep=";" --encoding=utf-8-sig
# python3 ../odoo_export_thread.py -c conf/connection_download.conf --file=retrieved/sale.order_update.csv --model='sale.order' --worker=1 --size=200 --domain="[]" --field="id,__last_update,create_date,name,partner_id:id,type_order,partner_invoice_id:id,partner_shipping_id:id,confirmation_date,pricelist_id:id,payment_term_id:id,client_order_ref,array_id:id,state,fiscal_position_id:id,invoice_status,force_invoiced,warehouse_id:id,user_id:id,agent_id:id,team_id:id,date_order" --sep=";" --encoding=utf-8-sig
# python3 ../odoo_export_thread.py -c conf/connection_download.conf --file=retrieved/sale.blanket.order.line.csv --model='sale.blanket.order.line' --worker=1 --size=200 --domain="[]" --field="id,name,original_uom_qty,price_unit,product_id:id,sequence,taxes_id:id,product_uom:id,order_id:id" --sep=";" --encoding=utf-8-sig
# python3 ../odoo_export_thread.py -c conf/connection_download.conf --file=retrieved/sale.order.line.csv --model='sale.order.line' --worker=1 --size=200 --domain="[]" --field="id,name,create_date,blanket_order_line:id,order_partner_id:id,tax_id:id,price_unit,product_id:id,create_uid:id,base_price,product_qty,product_uom_qty,qty_delivered,qty_to_invoice,qty_invoiced,order_id:id,order_id/name,da_discount,sequence,invoice_status,state,product_uom:id" --sep=";" --encoding=utf-8-sig
# python3 ../odoo_export_thread.py -c conf/connection_download.conf --file=retrieved/repair.order.csv --model='repair.order' --worker=1 --size=200 --domain="[]" --field="id,name,product_id:id,product_qty,product_uom:id,lot_id:id,date_planned,user_id:id,partner_id:id,address_id:id,location_id:id,guarantee_limit,invoice_method,partner_invoice_id:id,pricelist_id:id,state,internal_notes,quotation_notes,repaired,invoiced" --sep=";" --encoding=utf-8-sig
# python3 ../odoo_export_thread.py -c conf/connection_download.conf --file=retrieved/repair.line.csv --model='repair.line' --worker=1 --size=200 --domain="[]" --field="id,type,product_id:id,name,product_uom_qty,product_uom:id,price_unit,tax_id:id,location_id:id,location_dest_id:id,lot_id:id,state,repair_id:id,invoiced" --sep=";" --encoding=utf-8-sig
# python3 ../odoo_export_thread.py -c conf/connection_download.conf --file=retrieved/account.move.csv --model='account.move' --worker=1 --size=200 --domain="[]" --field="id,name,date,ref,move_type,journal_id:id,create_uid:id,dummy_account_id:id,narration,partner_id:id,reverse_date,reverse_entry_id:id,state" --sep=";" --encoding=utf-8-sig
# python3 ../odoo_export_thread.py -c conf/connection_download.conf --file=retrieved/account.full.reconcile.csv --model='account.full.reconcile' --worker=1 --size=200 --domain="[]" --field="id,name" --sep=";" --encoding=utf-8-sig
python3 ../odoo_export_thread.py -c conf/connection_download.conf --file=retrieved/account.move.line.ids.csv --model='account.move.line' --worker=1 --size=200 --domain="[]" --field="id,name,credit,tax_exigible,debit,date,date_maturity,account_id:id,amount_currency,amount_residual,amount_residual_currency,withholding_tax_base,withholding_tax_amount,tax_ids/id,tax_ids/ids,full_reconcile_id:id,partner_id:id,product_id:id,quantity,move_id,journal_id:id,ref,withholding_tax_id:id,product_uom_id:id,parent_state,invoice_origin,partner_ref,user_type_id:id" --sep=";" --encoding=utf-8-sig