#!/usr/bin/env bash

# python3 ../odoo_export_thread.py -c conf/connection_download.conf --file=retrieved/1_hr.department.csv --model='hr.department' --worker=1 --size=200 --domain="[]" --field="id,codice,name" --sep=";" --encoding=utf-8-sig
# python3 ../odoo_export_thread.py -c conf/connection_download.conf --file=retrieved/account.full.reconcile.csv --model='account.full.reconcile' --worker=1 --size=200 --domain="[]" --field="id,name" --sep=";" --encoding=utf-8-sig
# python3 ../odoo_export_thread.py -c conf/connection_download.conf --file=retrieved/10a_account.analytic.distribution.csv --model='account.analytic.distribution' --worker=1 --size=1 --domain="[]" --field="id,account_id,percentage,tag_id" --sep=";" --encoding=utf-8-sig
# python3 ../odoo_export_thread.py -c conf/connection_download.conf --file=retrieved/12_sync_employee.doctor.csv --model='sync_employee.doctor' --worker=1 --size=1 --domain="[]" --field="id,name,nome,cognome,anestesista,chirurgo,sinid,fiscalcode,work_email,department_id/id,department_id_m2m/id" --sep=";" --encoding=utf-8-sig
# python3 ../odoo_export_thread.py -c conf/connection_download.conf --file=retrieved/13_sync_employee.nurse.csv --model='sync_employee.nurse' --worker=1 --size=1 --domain="[]" --field="id,name,nome,cognome,sinid,fiscalcode,work_email,caposala,department_id/id,strumentista" --sep=";" --encoding=utf-8-sig
# python3 ../odoo_export_thread.py -c conf/connection_download.conf --file=retrieved/14_sync_employee.other_employee.csv --model='sync_employee.other_employee' --worker=1 --size=1 --domain="[]" --field="id,name,nome,cognome,sinid,fiscalcode,work_email" --sep=";" --encoding=utf-8-sig
# python3 ../odoo_export_thread.py -c conf/connection_download.conf --file=retrieved/16a_sync_product.service_type.csv --model='sync_product.service_type' --worker=1 --size=1 --domain="[]" --field="id,name,company_id/id" --sep=";" --encoding=utf-8-sig
# python3 ../odoo_export_thread.py -c conf/connection_download.conf --file=retrieved/18_product.pricelist.csv --model='product.pricelist' --worker=1 --size=1 --domain="[]" --field="id,name,discount_policy,type_franc,value_franc,currency_id/id,is_internal,is_ssn" --sep=";" --encoding=utf-8-sig
python3 ../odoo_export_thread.py -c conf/connection_download.conf --file=retrieved/18a_product.pricelist.item.csv --model='product.pricelist.item' --worker=1 --size=1 --domain="[]" --field="id,pricelist_id,name,applied_on,product_tmpl_id,compute_price,fixed_price,min_quantity,date_start,date_end" --sep=";" --encoding=utf-8-sig